load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

_ZAP_BUILD_FILE_CONTENT = """
load("@rules_zig//zig:defs.bzl", "zig_module")

zig_module(
    name = "zap_module",
    srcs = glob(["src/**/*.zig"]),
    main = "src/zap.zig",
    visibility = ["//visibility:public"],
)
"""

http_archive(
    name = "zap_archive",
    build_file_content = _ZAP_BUILD_FILE_CONTENT,
    sha256 = "697759c10aba616dd7d07d339e63e3f3233ba1ee934b8061ec574e9867dd27ec",
    strip_prefix = "zap-0.9.1",
    url = "https://github.com/zigzap/zap/archive/refs/tags/v0.9.1.tar.gz",
)
